# Docker 环境 Nginx 配置，/api 代理至 backend 服务
server {
    listen 81;
    # server_name 用来匹配请求里的域名。_ 表示匹配所有域名。
    server_name _;

    # 开启gzip压缩
    gzip on;
    # 压缩的最小长度
    gzip_min_length 1k;
    # 压缩级别
    gzip_comp_level 9;
    # 压缩的文件类型
    gzip_types text/plain text/css text/javascript application/json application/javascript application/x-javascript application/xml;
    # 是否在响应头中添加vary头，用来告知客户端应使用哪种不同的首部来接收响应。
    gzip_vary on;
    # 禁用IE6及以下版本的gzip压缩
    gzip_disable "MSIE [1-6]\.";

    # 根目录
    root /usr/share/nginx/html;
    # 引入mime.types文件
    include /etc/nginx/mime.types;

    # 处理根路径请求
    location / {
        # 尝试匹配文件或目录，如果匹配不到，则返回index.html
        try_files $uri $uri/ /index.html;
    }

    # 处理/api路径请求
    location /api/ {
        resolver 127.0.0.11 ipv6=off valid=30s;
        set $backend_upstream backend:8088;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://$backend_upstream;
        client_max_body_size 100M;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}