# 定义HTTP服务器
server {
    listen 80;
    server_name zhuyuxi.xyz www.zhuyuxi.xyz;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html =404;
    }

    # /api/* -> backend/*
    location /api/ {
        proxy_pass http://127.0.0.1:8088/;
        client_max_body_size 100M;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # music/api reverse proxy
    location /wapi/ {
        proxy_pass http://127.0.0.1:3000/;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
        root /usr/share/nginx/html;
    }
}

server {
    listen 80;
    server_name admin.zhuyuxi.xyz;

    location / {
        proxy_pass http://127.0.0.1:81/;
        client_max_body_size 100M;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name image.zhuyuxi.xyz;

    # image.zhuyuxi.xyz/* -> minio
    location / {
        proxy_pass http://127.0.0.1:9000;
        client_max_body_size 100M;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}