address: 0.0.0.0
port: 6065
behindProxy: true
directory: /data
permissions: CRUD

log:
  format: json

users:
  - username: "{env}WEBDAV_USERNAME"
    password: "{env}WEBDAV_PASSWORD"
    permissions: CRUD
